### ISSUE TITLE
Too long text description not working | Around 2000 lines

### ISSUE THREAD

**Issue by RasheshAccenture** [NuPlay/ExpandableText#7]
Hello Author,

_Thank you for this Wonderful library._

I have just identified an issue.
When the text is **too long (around 2000 lines)** the Text showing only **1 line with Read More** button.
When tapping on **Read More** it is expanding but up to certain limit not entire 2000 lines.

Can you please check this scenario at your end and provide solution ASAP?
As I've integrated this library in live project, I need to provide solution as soon as possible.

**Example text** _(which is not working)_

`Welcome all to the ChelseaFC Community here you can get the latest update on our players fan community groups Welcome all to the ChelseaFC Community here you can get the latest update on our players fan community groupsWelcome all to the ChelseaFC Community here you can get the latest update on our players fan community groupsWelcome all to the ChelseaFC Community here you can get the latest update on our players fan community groupsWelcome all to the ChelseaFC Community here you can get the latest update on our players fan community groups Welcome all to the ChelseaFC Community here you can get the latest update on our players fan community groups`

Thank you,
Rashesh

**Comment by NuPlay** [comment]
I'll fix it as soon as possible.

**Comment by NuPlay** [comment]
The problem seems to be because the view is drawn too large.
That's because SwiftUI can't draw such a large view.

If you need to display such a long text

I think you should separate the text and use something like List or LazyVStack with Lazy property.

It seems difficult to modify this library to solve the problem.

I'm sorry I couldn't help you solve the problem
